### ISSUE TITLE
Image not available on the Docker Hub

### ISSUE THREAD

**Issue by fbartels** [univention/ucs-appliance-container#1]
Hi,

the readme states that there should be an image available at `univention/univention-corporate-server` but this cannot be found on the Docker Hub. Is it set as private?

**Comment by GinoHarlos** [comment]
Hi Felix,

i think it's coming soon ...

For now you could use the [build-readme](../blob/main/docs/README.BUILD.md) guide. This takes round 15 to 30 min, if you start from scratch.

**Comment by JOduMonT** [comment]
I think we are talking about the same "[container image](https://hub.docker.com/r/univention/univention-corporate-server)"

I found the example showed have error
```
FQDN=node.ucs.example; \
docker run \
--detach \
--cap-add SYS_ADMIN \
--cap-add MKNOD \
--volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
--tmpfs /run \
--tmpfs /tmp \
--restart unless-stopped \
--hostname ${FQDN} \
--name ${FQDN} \
univention-corporate-server
```


it should end with **univention/univention-corporate-server** and not simply ~univention-corporate-server~

**Comment by reqa** [comment]
Thanks for pointing that out, I've adjusted the example.
